// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	kafka "github.com/kuromii5/chat-bot-chat-service/internal/adapters/kafka"
	mock "github.com/stretchr/testify/mock"
)

// MockKafkaNotifier is an autogenerated mock type for the KafkaNotifier type
type MockKafkaNotifier struct {
	mock.Mock
}

type MockKafkaNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKafkaNotifier) EXPECT() *MockKafkaNotifier_Expecter {
	return &MockKafkaNotifier_Expecter{mock: &_m.Mock}
}

// PublishNotification provides a mock function with given fields: ctx, event
func (_m *MockKafkaNotifier) PublishNotification(ctx context.Context, event kafka.NotificationEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, kafka.NotificationEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockKafkaNotifier_PublishNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishNotification'
type MockKafkaNotifier_PublishNotification_Call struct {
	*mock.Call
}

// PublishNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - event kafka.NotificationEvent
func (_e *MockKafkaNotifier_Expecter) PublishNotification(ctx interface{}, event interface{}) *MockKafkaNotifier_PublishNotification_Call {
	return &MockKafkaNotifier_PublishNotification_Call{Call: _e.mock.On("PublishNotification", ctx, event)}
}

func (_c *MockKafkaNotifier_PublishNotification_Call) Run(run func(ctx context.Context, event kafka.NotificationEvent)) *MockKafkaNotifier_PublishNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(kafka.NotificationEvent))
	})
	return _c
}

func (_c *MockKafkaNotifier_PublishNotification_Call) Return(_a0 error) *MockKafkaNotifier_PublishNotification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockKafkaNotifier_PublishNotification_Call) RunAndReturn(run func(context.Context, kafka.NotificationEvent) error) *MockKafkaNotifier_PublishNotification_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockKafkaNotifier creates a new instance of MockKafkaNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKafkaNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKafkaNotifier {
	mock := &MockKafkaNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
