// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/kuromii5/chat-bot-chat-service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockOutboxRepo is an autogenerated mock type for the OutboxRepo type
type MockOutboxRepo struct {
	mock.Mock
}

type MockOutboxRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutboxRepo) EXPECT() *MockOutboxRepo_Expecter {
	return &MockOutboxRepo_Expecter{mock: &_m.Mock}
}

// FetchPending provides a mock function with given fields: ctx, limit
func (_m *MockOutboxRepo) FetchPending(ctx context.Context, limit int) ([]*domain.OutboxEvent, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for FetchPending")
	}

	var r0 []*domain.OutboxEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*domain.OutboxEvent, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*domain.OutboxEvent); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.OutboxEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOutboxRepo_FetchPending_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchPending'
type MockOutboxRepo_FetchPending_Call struct {
	*mock.Call
}

// FetchPending is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockOutboxRepo_Expecter) FetchPending(ctx interface{}, limit interface{}) *MockOutboxRepo_FetchPending_Call {
	return &MockOutboxRepo_FetchPending_Call{Call: _e.mock.On("FetchPending", ctx, limit)}
}

func (_c *MockOutboxRepo_FetchPending_Call) Run(run func(ctx context.Context, limit int)) *MockOutboxRepo_FetchPending_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockOutboxRepo_FetchPending_Call) Return(_a0 []*domain.OutboxEvent, _a1 error) *MockOutboxRepo_FetchPending_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOutboxRepo_FetchPending_Call) RunAndReturn(run func(context.Context, int) ([]*domain.OutboxEvent, error)) *MockOutboxRepo_FetchPending_Call {
	_c.Call.Return(run)
	return _c
}

// MarkFailed provides a mock function with given fields: ctx, id, errMsg
func (_m *MockOutboxRepo) MarkFailed(ctx context.Context, id uuid.UUID, errMsg string) error {
	ret := _m.Called(ctx, id, errMsg)

	if len(ret) == 0 {
		panic("no return value specified for MarkFailed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, id, errMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOutboxRepo_MarkFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFailed'
type MockOutboxRepo_MarkFailed_Call struct {
	*mock.Call
}

// MarkFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - errMsg string
func (_e *MockOutboxRepo_Expecter) MarkFailed(ctx interface{}, id interface{}, errMsg interface{}) *MockOutboxRepo_MarkFailed_Call {
	return &MockOutboxRepo_MarkFailed_Call{Call: _e.mock.On("MarkFailed", ctx, id, errMsg)}
}

func (_c *MockOutboxRepo_MarkFailed_Call) Run(run func(ctx context.Context, id uuid.UUID, errMsg string)) *MockOutboxRepo_MarkFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockOutboxRepo_MarkFailed_Call) Return(_a0 error) *MockOutboxRepo_MarkFailed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOutboxRepo_MarkFailed_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockOutboxRepo_MarkFailed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkPublished provides a mock function with given fields: ctx, id
func (_m *MockOutboxRepo) MarkPublished(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkPublished")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOutboxRepo_MarkPublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkPublished'
type MockOutboxRepo_MarkPublished_Call struct {
	*mock.Call
}

// MarkPublished is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockOutboxRepo_Expecter) MarkPublished(ctx interface{}, id interface{}) *MockOutboxRepo_MarkPublished_Call {
	return &MockOutboxRepo_MarkPublished_Call{Call: _e.mock.On("MarkPublished", ctx, id)}
}

func (_c *MockOutboxRepo_MarkPublished_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockOutboxRepo_MarkPublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOutboxRepo_MarkPublished_Call) Return(_a0 error) *MockOutboxRepo_MarkPublished_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOutboxRepo_MarkPublished_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockOutboxRepo_MarkPublished_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOutboxRepo creates a new instance of MockOutboxRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutboxRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutboxRepo {
	mock := &MockOutboxRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
