// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/kuromii5/chat-bot-chat-service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockPublisher is an autogenerated mock type for the Publisher type
type MockPublisher struct {
	mock.Mock
}

type MockPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublisher) EXPECT() *MockPublisher_Expecter {
	return &MockPublisher_Expecter{mock: &_m.Mock}
}

// PublishAIReply provides a mock function with given fields: ctx, humanID, msg
func (_m *MockPublisher) PublishAIReply(ctx context.Context, humanID uuid.UUID, msg *domain.Message) error {
	ret := _m.Called(ctx, humanID, msg)

	if len(ret) == 0 {
		panic("no return value specified for PublishAIReply")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.Message) error); ok {
		r0 = rf(ctx, humanID, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPublisher_PublishAIReply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishAIReply'
type MockPublisher_PublishAIReply_Call struct {
	*mock.Call
}

// PublishAIReply is a helper method to define mock.On call
//   - ctx context.Context
//   - humanID uuid.UUID
//   - msg *domain.Message
func (_e *MockPublisher_Expecter) PublishAIReply(ctx interface{}, humanID interface{}, msg interface{}) *MockPublisher_PublishAIReply_Call {
	return &MockPublisher_PublishAIReply_Call{Call: _e.mock.On("PublishAIReply", ctx, humanID, msg)}
}

func (_c *MockPublisher_PublishAIReply_Call) Run(run func(ctx context.Context, humanID uuid.UUID, msg *domain.Message)) *MockPublisher_PublishAIReply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*domain.Message))
	})
	return _c
}

func (_c *MockPublisher_PublishAIReply_Call) Return(_a0 error) *MockPublisher_PublishAIReply_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPublisher_PublishAIReply_Call) RunAndReturn(run func(context.Context, uuid.UUID, *domain.Message) error) *MockPublisher_PublishAIReply_Call {
	_c.Call.Return(run)
	return _c
}

// PublishFollowUp provides a mock function with given fields: ctx, roomID, msg
func (_m *MockPublisher) PublishFollowUp(ctx context.Context, roomID uuid.UUID, msg *domain.Message) error {
	ret := _m.Called(ctx, roomID, msg)

	if len(ret) == 0 {
		panic("no return value specified for PublishFollowUp")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.Message) error); ok {
		r0 = rf(ctx, roomID, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPublisher_PublishFollowUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishFollowUp'
type MockPublisher_PublishFollowUp_Call struct {
	*mock.Call
}

// PublishFollowUp is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - msg *domain.Message
func (_e *MockPublisher_Expecter) PublishFollowUp(ctx interface{}, roomID interface{}, msg interface{}) *MockPublisher_PublishFollowUp_Call {
	return &MockPublisher_PublishFollowUp_Call{Call: _e.mock.On("PublishFollowUp", ctx, roomID, msg)}
}

func (_c *MockPublisher_PublishFollowUp_Call) Run(run func(ctx context.Context, roomID uuid.UUID, msg *domain.Message)) *MockPublisher_PublishFollowUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*domain.Message))
	})
	return _c
}

func (_c *MockPublisher_PublishFollowUp_Call) Return(_a0 error) *MockPublisher_PublishFollowUp_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPublisher_PublishFollowUp_Call) RunAndReturn(run func(context.Context, uuid.UUID, *domain.Message) error) *MockPublisher_PublishFollowUp_Call {
	_c.Call.Return(run)
	return _c
}

// PublishNewQuestion provides a mock function with given fields: ctx, msg
func (_m *MockPublisher) PublishNewQuestion(ctx context.Context, msg *domain.Message) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for PublishNewQuestion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Message) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPublisher_PublishNewQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishNewQuestion'
type MockPublisher_PublishNewQuestion_Call struct {
	*mock.Call
}

// PublishNewQuestion is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *domain.Message
func (_e *MockPublisher_Expecter) PublishNewQuestion(ctx interface{}, msg interface{}) *MockPublisher_PublishNewQuestion_Call {
	return &MockPublisher_PublishNewQuestion_Call{Call: _e.mock.On("PublishNewQuestion", ctx, msg)}
}

func (_c *MockPublisher_PublishNewQuestion_Call) Run(run func(ctx context.Context, msg *domain.Message)) *MockPublisher_PublishNewQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Message))
	})
	return _c
}

func (_c *MockPublisher_PublishNewQuestion_Call) Return(_a0 error) *MockPublisher_PublishNewQuestion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPublisher_PublishNewQuestion_Call) RunAndReturn(run func(context.Context, *domain.Message) error) *MockPublisher_PublishNewQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPublisher creates a new instance of MockPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublisher {
	mock := &MockPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
