// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockQueueSyncer is an autogenerated mock type for the QueueSyncer type
type MockQueueSyncer struct {
	mock.Mock
}

type MockQueueSyncer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueueSyncer) EXPECT() *MockQueueSyncer_Expecter {
	return &MockQueueSyncer_Expecter{mock: &_m.Mock}
}

// SyncAIQueue provides a mock function with given fields: ctx, aiID, tags, oldTags
func (_m *MockQueueSyncer) SyncAIQueue(ctx context.Context, aiID uuid.UUID, tags []string, oldTags []string) error {
	ret := _m.Called(ctx, aiID, tags, oldTags)

	if len(ret) == 0 {
		panic("no return value specified for SyncAIQueue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string, []string) error); ok {
		r0 = rf(ctx, aiID, tags, oldTags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQueueSyncer_SyncAIQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncAIQueue'
type MockQueueSyncer_SyncAIQueue_Call struct {
	*mock.Call
}

// SyncAIQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - aiID uuid.UUID
//   - tags []string
//   - oldTags []string
func (_e *MockQueueSyncer_Expecter) SyncAIQueue(ctx interface{}, aiID interface{}, tags interface{}, oldTags interface{}) *MockQueueSyncer_SyncAIQueue_Call {
	return &MockQueueSyncer_SyncAIQueue_Call{Call: _e.mock.On("SyncAIQueue", ctx, aiID, tags, oldTags)}
}

func (_c *MockQueueSyncer_SyncAIQueue_Call) Run(run func(ctx context.Context, aiID uuid.UUID, tags []string, oldTags []string)) *MockQueueSyncer_SyncAIQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]string), args[3].([]string))
	})
	return _c
}

func (_c *MockQueueSyncer_SyncAIQueue_Call) Return(_a0 error) *MockQueueSyncer_SyncAIQueue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueueSyncer_SyncAIQueue_Call) RunAndReturn(run func(context.Context, uuid.UUID, []string, []string) error) *MockQueueSyncer_SyncAIQueue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueueSyncer creates a new instance of MockQueueSyncer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueueSyncer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueueSyncer {
	mock := &MockQueueSyncer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
