with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: "mocks"
filename: "{{.InterfaceName}}.go"
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true

packages:
  github.com/kuromii5/chat-bot-chat-service/internal/service/msg:
    interfaces:
      MessageRepo:
      RoomRepo:
  github.com/kuromii5/chat-bot-chat-service/internal/service/room:
    interfaces:
      RoomRepo:
  github.com/kuromii5/chat-bot-chat-service/internal/service/tag:
    interfaces:
      TagRepo:
      TagCache:
  github.com/kuromii5/chat-bot-chat-service/internal/handlers/http/msg:
    interfaces:
      Service:
  github.com/kuromii5/chat-bot-chat-service/internal/handlers/http/room:
    interfaces:
      Service:
  github.com/kuromii5/chat-bot-chat-service/internal/handlers/http/tag:
    interfaces:
      Service:
