// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockBinder is an autogenerated mock type for the Binder type
type MockBinder struct {
	mock.Mock
}

type MockBinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBinder) EXPECT() *MockBinder_Expecter {
	return &MockBinder_Expecter{mock: &_m.Mock}
}

// BindRoomToAI provides a mock function with given fields: ctx, roomID, aiID
func (_m *MockBinder) BindRoomToAI(ctx context.Context, roomID uuid.UUID, aiID uuid.UUID) error {
	ret := _m.Called(ctx, roomID, aiID)

	if len(ret) == 0 {
		panic("no return value specified for BindRoomToAI")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, roomID, aiID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBinder_BindRoomToAI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindRoomToAI'
type MockBinder_BindRoomToAI_Call struct {
	*mock.Call
}

// BindRoomToAI is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - aiID uuid.UUID
func (_e *MockBinder_Expecter) BindRoomToAI(ctx interface{}, roomID interface{}, aiID interface{}) *MockBinder_BindRoomToAI_Call {
	return &MockBinder_BindRoomToAI_Call{Call: _e.mock.On("BindRoomToAI", ctx, roomID, aiID)}
}

func (_c *MockBinder_BindRoomToAI_Call) Run(run func(ctx context.Context, roomID uuid.UUID, aiID uuid.UUID)) *MockBinder_BindRoomToAI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockBinder_BindRoomToAI_Call) Return(_a0 error) *MockBinder_BindRoomToAI_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBinder_BindRoomToAI_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockBinder_BindRoomToAI_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBinder creates a new instance of MockBinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBinder {
	mock := &MockBinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
