// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/kuromii5/chat-bot-chat-service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockMessageRepo is an autogenerated mock type for the MessageRepo type
type MockMessageRepo struct {
	mock.Mock
}

type MockMessageRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageRepo) EXPECT() *MockMessageRepo_Expecter {
	return &MockMessageRepo_Expecter{mock: &_m.Mock}
}

// GetLastMessage provides a mock function with given fields: ctx, roomID
func (_m *MockMessageRepo) GetLastMessage(ctx context.Context, roomID uuid.UUID) (*domain.Message, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetLastMessage")
	}

	var r0 *domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Message, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Message); ok {
		r0 = rf(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageRepo_GetLastMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastMessage'
type MockMessageRepo_GetLastMessage_Call struct {
	*mock.Call
}

// GetLastMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
func (_e *MockMessageRepo_Expecter) GetLastMessage(ctx interface{}, roomID interface{}) *MockMessageRepo_GetLastMessage_Call {
	return &MockMessageRepo_GetLastMessage_Call{Call: _e.mock.On("GetLastMessage", ctx, roomID)}
}

func (_c *MockMessageRepo_GetLastMessage_Call) Run(run func(ctx context.Context, roomID uuid.UUID)) *MockMessageRepo_GetLastMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockMessageRepo_GetLastMessage_Call) Return(_a0 *domain.Message, _a1 error) *MockMessageRepo_GetLastMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageRepo_GetLastMessage_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Message, error)) *MockMessageRepo_GetLastMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SaveWithOutbox provides a mock function with given fields: ctx, _a1, eventType, recipientID
func (_m *MockMessageRepo) SaveWithOutbox(ctx context.Context, _a1 *domain.Message, eventType domain.EventType, recipientID uuid.UUID) (*domain.Message, error) {
	ret := _m.Called(ctx, _a1, eventType, recipientID)

	if len(ret) == 0 {
		panic("no return value specified for SaveWithOutbox")
	}

	var r0 *domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Message, domain.EventType, uuid.UUID) (*domain.Message, error)); ok {
		return rf(ctx, _a1, eventType, recipientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Message, domain.EventType, uuid.UUID) *domain.Message); ok {
		r0 = rf(ctx, _a1, eventType, recipientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Message, domain.EventType, uuid.UUID) error); ok {
		r1 = rf(ctx, _a1, eventType, recipientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageRepo_SaveWithOutbox_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveWithOutbox'
type MockMessageRepo_SaveWithOutbox_Call struct {
	*mock.Call
}

// SaveWithOutbox is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *domain.Message
//   - eventType domain.EventType
//   - recipientID uuid.UUID
func (_e *MockMessageRepo_Expecter) SaveWithOutbox(ctx interface{}, _a1 interface{}, eventType interface{}, recipientID interface{}) *MockMessageRepo_SaveWithOutbox_Call {
	return &MockMessageRepo_SaveWithOutbox_Call{Call: _e.mock.On("SaveWithOutbox", ctx, _a1, eventType, recipientID)}
}

func (_c *MockMessageRepo_SaveWithOutbox_Call) Run(run func(ctx context.Context, _a1 *domain.Message, eventType domain.EventType, recipientID uuid.UUID)) *MockMessageRepo_SaveWithOutbox_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Message), args[2].(domain.EventType), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockMessageRepo_SaveWithOutbox_Call) Return(_a0 *domain.Message, _a1 error) *MockMessageRepo_SaveWithOutbox_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageRepo_SaveWithOutbox_Call) RunAndReturn(run func(context.Context, *domain.Message, domain.EventType, uuid.UUID) (*domain.Message, error)) *MockMessageRepo_SaveWithOutbox_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageRepo creates a new instance of MockMessageRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageRepo {
	mock := &MockMessageRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
