// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/kuromii5/chat-bot-chat-service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockMessageRepo is an autogenerated mock type for the MessageRepo type
type MockMessageRepo struct {
	mock.Mock
}

type MockMessageRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageRepo) EXPECT() *MockMessageRepo_Expecter {
	return &MockMessageRepo_Expecter{mock: &_m.Mock}
}

// GetLastMessages provides a mock function with given fields: ctx, roomID, limit
func (_m *MockMessageRepo) GetLastMessages(ctx context.Context, roomID uuid.UUID, limit int) ([]*domain.Message, error) {
	ret := _m.Called(ctx, roomID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetLastMessages")
	}

	var r0 []*domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) ([]*domain.Message, error)); ok {
		return rf(ctx, roomID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) []*domain.Message); ok {
		r0 = rf(ctx, roomID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = rf(ctx, roomID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageRepo_GetLastMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastMessages'
type MockMessageRepo_GetLastMessages_Call struct {
	*mock.Call
}

// GetLastMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - limit int
func (_e *MockMessageRepo_Expecter) GetLastMessages(ctx interface{}, roomID interface{}, limit interface{}) *MockMessageRepo_GetLastMessages_Call {
	return &MockMessageRepo_GetLastMessages_Call{Call: _e.mock.On("GetLastMessages", ctx, roomID, limit)}
}

func (_c *MockMessageRepo_GetLastMessages_Call) Run(run func(ctx context.Context, roomID uuid.UUID, limit int)) *MockMessageRepo_GetLastMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *MockMessageRepo_GetLastMessages_Call) Return(_a0 []*domain.Message, _a1 error) *MockMessageRepo_GetLastMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageRepo_GetLastMessages_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) ([]*domain.Message, error)) *MockMessageRepo_GetLastMessages_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, _a1
func (_m *MockMessageRepo) Save(ctx context.Context, _a1 *domain.Message) (*domain.Message, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Message) (*domain.Message, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Message) *domain.Message); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Message) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageRepo_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockMessageRepo_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *domain.Message
func (_e *MockMessageRepo_Expecter) Save(ctx interface{}, _a1 interface{}) *MockMessageRepo_Save_Call {
	return &MockMessageRepo_Save_Call{Call: _e.mock.On("Save", ctx, _a1)}
}

func (_c *MockMessageRepo_Save_Call) Run(run func(ctx context.Context, _a1 *domain.Message)) *MockMessageRepo_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Message))
	})
	return _c
}

func (_c *MockMessageRepo_Save_Call) Return(_a0 *domain.Message, _a1 error) *MockMessageRepo_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageRepo_Save_Call) RunAndReturn(run func(context.Context, *domain.Message) (*domain.Message, error)) *MockMessageRepo_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageRepo creates a new instance of MockMessageRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageRepo {
	mock := &MockMessageRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
