// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/kuromii5/chat-bot-chat-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockNotifier is an autogenerated mock type for the Notifier type
type MockNotifier struct {
	mock.Mock
}

type MockNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifier) EXPECT() *MockNotifier_Expecter {
	return &MockNotifier_Expecter{mock: &_m.Mock}
}

// PublishNewQuestion provides a mock function with given fields: ctx, _a1
func (_m *MockNotifier) PublishNewQuestion(ctx context.Context, _a1 *domain.Message) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PublishNewQuestion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Message) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotifier_PublishNewQuestion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishNewQuestion'
type MockNotifier_PublishNewQuestion_Call struct {
	*mock.Call
}

// PublishNewQuestion is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *domain.Message
func (_e *MockNotifier_Expecter) PublishNewQuestion(ctx interface{}, _a1 interface{}) *MockNotifier_PublishNewQuestion_Call {
	return &MockNotifier_PublishNewQuestion_Call{Call: _e.mock.On("PublishNewQuestion", ctx, _a1)}
}

func (_c *MockNotifier_PublishNewQuestion_Call) Run(run func(ctx context.Context, _a1 *domain.Message)) *MockNotifier_PublishNewQuestion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Message))
	})
	return _c
}

func (_c *MockNotifier_PublishNewQuestion_Call) Return(_a0 error) *MockNotifier_PublishNewQuestion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotifier_PublishNewQuestion_Call) RunAndReturn(run func(context.Context, *domain.Message) error) *MockNotifier_PublishNewQuestion_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotifier creates a new instance of MockNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifier {
	mock := &MockNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
