// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/kuromii5/chat-bot-chat-service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRoomRepo is an autogenerated mock type for the RoomRepo type
type MockRoomRepo struct {
	mock.Mock
}

type MockRoomRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomRepo) EXPECT() *MockRoomRepo_Expecter {
	return &MockRoomRepo_Expecter{mock: &_m.Mock}
}

// CreateRoom provides a mock function with given fields: ctx, humanID
func (_m *MockRoomRepo) CreateRoom(ctx context.Context, humanID uuid.UUID) (*domain.Room, error) {
	ret := _m.Called(ctx, humanID)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoom")
	}

	var r0 *domain.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Room, error)); ok {
		return rf(ctx, humanID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Room); ok {
		r0 = rf(ctx, humanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, humanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomRepo_CreateRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRoom'
type MockRoomRepo_CreateRoom_Call struct {
	*mock.Call
}

// CreateRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - humanID uuid.UUID
func (_e *MockRoomRepo_Expecter) CreateRoom(ctx interface{}, humanID interface{}) *MockRoomRepo_CreateRoom_Call {
	return &MockRoomRepo_CreateRoom_Call{Call: _e.mock.On("CreateRoom", ctx, humanID)}
}

func (_c *MockRoomRepo_CreateRoom_Call) Run(run func(ctx context.Context, humanID uuid.UUID)) *MockRoomRepo_CreateRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRoomRepo_CreateRoom_Call) Return(_a0 *domain.Room, _a1 error) *MockRoomRepo_CreateRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomRepo_CreateRoom_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Room, error)) *MockRoomRepo_CreateRoom_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoom provides a mock function with given fields: ctx, roomID
func (_m *MockRoomRepo) GetRoom(ctx context.Context, roomID uuid.UUID) (*domain.Room, error) {
	ret := _m.Called(ctx, roomID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoom")
	}

	var r0 *domain.Room
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Room, error)); ok {
		return rf(ctx, roomID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Room); ok {
		r0 = rf(ctx, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Room)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, roomID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoomRepo_GetRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoom'
type MockRoomRepo_GetRoom_Call struct {
	*mock.Call
}

// GetRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
func (_e *MockRoomRepo_Expecter) GetRoom(ctx interface{}, roomID interface{}) *MockRoomRepo_GetRoom_Call {
	return &MockRoomRepo_GetRoom_Call{Call: _e.mock.On("GetRoom", ctx, roomID)}
}

func (_c *MockRoomRepo_GetRoom_Call) Run(run func(ctx context.Context, roomID uuid.UUID)) *MockRoomRepo_GetRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRoomRepo_GetRoom_Call) Return(_a0 *domain.Room, _a1 error) *MockRoomRepo_GetRoom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoomRepo_GetRoom_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Room, error)) *MockRoomRepo_GetRoom_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoomRepo creates a new instance of MockRoomRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomRepo {
	mock := &MockRoomRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
