// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// ClaimRoom provides a mock function with given fields: ctx, roomID, aiID
func (_m *MockService) ClaimRoom(ctx context.Context, roomID uuid.UUID, aiID uuid.UUID) error {
	ret := _m.Called(ctx, roomID, aiID)

	if len(ret) == 0 {
		panic("no return value specified for ClaimRoom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, roomID, aiID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_ClaimRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimRoom'
type MockService_ClaimRoom_Call struct {
	*mock.Call
}

// ClaimRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - aiID uuid.UUID
func (_e *MockService_Expecter) ClaimRoom(ctx interface{}, roomID interface{}, aiID interface{}) *MockService_ClaimRoom_Call {
	return &MockService_ClaimRoom_Call{Call: _e.mock.On("ClaimRoom", ctx, roomID, aiID)}
}

func (_c *MockService_ClaimRoom_Call) Run(run func(ctx context.Context, roomID uuid.UUID, aiID uuid.UUID)) *MockService_ClaimRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_ClaimRoom_Call) Return(_a0 error) *MockService_ClaimRoom_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_ClaimRoom_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockService_ClaimRoom_Call {
	_c.Call.Return(run)
	return _c
}

// CloseRoom provides a mock function with given fields: ctx, roomID, userID
func (_m *MockService) CloseRoom(ctx context.Context, roomID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CloseRoom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, roomID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_CloseRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseRoom'
type MockService_CloseRoom_Call struct {
	*mock.Call
}

// CloseRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) CloseRoom(ctx interface{}, roomID interface{}, userID interface{}) *MockService_CloseRoom_Call {
	return &MockService_CloseRoom_Call{Call: _e.mock.On("CloseRoom", ctx, roomID, userID)}
}

func (_c *MockService_CloseRoom_Call) Run(run func(ctx context.Context, roomID uuid.UUID, userID uuid.UUID)) *MockService_CloseRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_CloseRoom_Call) Return(_a0 error) *MockService_CloseRoom_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_CloseRoom_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockService_CloseRoom_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
