// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockNotifier is an autogenerated mock type for the Notifier type
type MockNotifier struct {
	mock.Mock
}

type MockNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifier) EXPECT() *MockNotifier_Expecter {
	return &MockNotifier_Expecter{mock: &_m.Mock}
}

// SyncAIQueue provides a mock function with given fields: ctx, userID, tags, oldTags
func (_m *MockNotifier) SyncAIQueue(ctx context.Context, userID uuid.UUID, tags []string, oldTags []string) error {
	ret := _m.Called(ctx, userID, tags, oldTags)

	if len(ret) == 0 {
		panic("no return value specified for SyncAIQueue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string, []string) error); ok {
		r0 = rf(ctx, userID, tags, oldTags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNotifier_SyncAIQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncAIQueue'
type MockNotifier_SyncAIQueue_Call struct {
	*mock.Call
}

// SyncAIQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - tags []string
//   - oldTags []string
func (_e *MockNotifier_Expecter) SyncAIQueue(ctx interface{}, userID interface{}, tags interface{}, oldTags interface{}) *MockNotifier_SyncAIQueue_Call {
	return &MockNotifier_SyncAIQueue_Call{Call: _e.mock.On("SyncAIQueue", ctx, userID, tags, oldTags)}
}

func (_c *MockNotifier_SyncAIQueue_Call) Run(run func(ctx context.Context, userID uuid.UUID, tags []string, oldTags []string)) *MockNotifier_SyncAIQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]string), args[3].([]string))
	})
	return _c
}

func (_c *MockNotifier_SyncAIQueue_Call) Return(_a0 error) *MockNotifier_SyncAIQueue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNotifier_SyncAIQueue_Call) RunAndReturn(run func(context.Context, uuid.UUID, []string, []string) error) *MockNotifier_SyncAIQueue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotifier creates a new instance of MockNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifier {
	mock := &MockNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
