// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTagCache is an autogenerated mock type for the TagCache type
type MockTagCache struct {
	mock.Mock
}

type MockTagCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagCache) EXPECT() *MockTagCache_Expecter {
	return &MockTagCache_Expecter{mock: &_m.Mock}
}

// AreTagsValid provides a mock function with given fields: ctx, tags
func (_m *MockTagCache) AreTagsValid(ctx context.Context, tags []string) bool {
	ret := _m.Called(ctx, tags)

	if len(ret) == 0 {
		panic("no return value specified for AreTagsValid")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, []string) bool); ok {
		r0 = rf(ctx, tags)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockTagCache_AreTagsValid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AreTagsValid'
type MockTagCache_AreTagsValid_Call struct {
	*mock.Call
}

// AreTagsValid is a helper method to define mock.On call
//   - ctx context.Context
//   - tags []string
func (_e *MockTagCache_Expecter) AreTagsValid(ctx interface{}, tags interface{}) *MockTagCache_AreTagsValid_Call {
	return &MockTagCache_AreTagsValid_Call{Call: _e.mock.On("AreTagsValid", ctx, tags)}
}

func (_c *MockTagCache_AreTagsValid_Call) Run(run func(ctx context.Context, tags []string)) *MockTagCache_AreTagsValid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockTagCache_AreTagsValid_Call) Return(_a0 bool) *MockTagCache_AreTagsValid_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTagCache_AreTagsValid_Call) RunAndReturn(run func(context.Context, []string) bool) *MockTagCache_AreTagsValid_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTagCache creates a new instance of MockTagCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagCache {
	mock := &MockTagCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
