// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTagRepo is an autogenerated mock type for the TagRepo type
type MockTagRepo struct {
	mock.Mock
}

type MockTagRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTagRepo) EXPECT() *MockTagRepo_Expecter {
	return &MockTagRepo_Expecter{mock: &_m.Mock}
}

// GetProfileTags provides a mock function with given fields: ctx, userID
func (_m *MockTagRepo) GetProfileTags(ctx context.Context, userID uuid.UUID) ([]string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileTags")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []string); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTagRepo_GetProfileTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfileTags'
type MockTagRepo_GetProfileTags_Call struct {
	*mock.Call
}

// GetProfileTags is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockTagRepo_Expecter) GetProfileTags(ctx interface{}, userID interface{}) *MockTagRepo_GetProfileTags_Call {
	return &MockTagRepo_GetProfileTags_Call{Call: _e.mock.On("GetProfileTags", ctx, userID)}
}

func (_c *MockTagRepo_GetProfileTags_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockTagRepo_GetProfileTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTagRepo_GetProfileTags_Call) Return(_a0 []string, _a1 error) *MockTagRepo_GetProfileTags_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTagRepo_GetProfileTags_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]string, error)) *MockTagRepo_GetProfileTags_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfileTags provides a mock function with given fields: ctx, userID, tags
func (_m *MockTagRepo) UpdateProfileTags(ctx context.Context, userID uuid.UUID, tags []string) ([]string, error) {
	ret := _m.Called(ctx, userID, tags)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfileTags")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string) ([]string, error)); ok {
		return rf(ctx, userID, tags)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string) []string); ok {
		r0 = rf(ctx, userID, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, []string) error); ok {
		r1 = rf(ctx, userID, tags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTagRepo_UpdateProfileTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfileTags'
type MockTagRepo_UpdateProfileTags_Call struct {
	*mock.Call
}

// UpdateProfileTags is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - tags []string
func (_e *MockTagRepo_Expecter) UpdateProfileTags(ctx interface{}, userID interface{}, tags interface{}) *MockTagRepo_UpdateProfileTags_Call {
	return &MockTagRepo_UpdateProfileTags_Call{Call: _e.mock.On("UpdateProfileTags", ctx, userID, tags)}
}

func (_c *MockTagRepo_UpdateProfileTags_Call) Run(run func(ctx context.Context, userID uuid.UUID, tags []string)) *MockTagRepo_UpdateProfileTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]string))
	})
	return _c
}

func (_c *MockTagRepo_UpdateProfileTags_Call) Return(oldTags []string, err error) *MockTagRepo_UpdateProfileTags_Call {
	_c.Call.Return(oldTags, err)
	return _c
}

func (_c *MockTagRepo_UpdateProfileTags_Call) RunAndReturn(run func(context.Context, uuid.UUID, []string) ([]string, error)) *MockTagRepo_UpdateProfileTags_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTagRepo creates a new instance of MockTagRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTagRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTagRepo {
	mock := &MockTagRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
