// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetProfileTags provides a mock function with given fields: ctx, userID
func (_m *MockService) GetProfileTags(ctx context.Context, userID uuid.UUID) ([]string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfileTags")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []string); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetProfileTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfileTags'
type MockService_GetProfileTags_Call struct {
	*mock.Call
}

// GetProfileTags is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockService_Expecter) GetProfileTags(ctx interface{}, userID interface{}) *MockService_GetProfileTags_Call {
	return &MockService_GetProfileTags_Call{Call: _e.mock.On("GetProfileTags", ctx, userID)}
}

func (_c *MockService_GetProfileTags_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockService_GetProfileTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_GetProfileTags_Call) Return(_a0 []string, _a1 error) *MockService_GetProfileTags_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetProfileTags_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]string, error)) *MockService_GetProfileTags_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfileTags provides a mock function with given fields: ctx, userID, tags
func (_m *MockService) UpdateProfileTags(ctx context.Context, userID uuid.UUID, tags []string) error {
	ret := _m.Called(ctx, userID, tags)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfileTags")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []string) error); ok {
		r0 = rf(ctx, userID, tags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_UpdateProfileTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfileTags'
type MockService_UpdateProfileTags_Call struct {
	*mock.Call
}

// UpdateProfileTags is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - tags []string
func (_e *MockService_Expecter) UpdateProfileTags(ctx interface{}, userID interface{}, tags interface{}) *MockService_UpdateProfileTags_Call {
	return &MockService_UpdateProfileTags_Call{Call: _e.mock.On("UpdateProfileTags", ctx, userID, tags)}
}

func (_c *MockService_UpdateProfileTags_Call) Run(run func(ctx context.Context, userID uuid.UUID, tags []string)) *MockService_UpdateProfileTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]string))
	})
	return _c
}

func (_c *MockService_UpdateProfileTags_Call) Return(_a0 error) *MockService_UpdateProfileTags_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_UpdateProfileTags_Call) RunAndReturn(run func(context.Context, uuid.UUID, []string) error) *MockService_UpdateProfileTags_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
