// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/kuromii5/chat-bot-chat-service/internal/domain"

	mock "github.com/stretchr/testify/mock"

	msg "github.com/kuromii5/chat-bot-chat-service/internal/service/msg"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// SendMessage provides a mock function with given fields: ctx, req
func (_m *MockService) SendMessage(ctx context.Context, req msg.CreateMessageReq) (*domain.Message, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 *domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, msg.CreateMessageReq) (*domain.Message, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, msg.CreateMessageReq) *domain.Message); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, msg.CreateMessageReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockService_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - req msg.CreateMessageReq
func (_e *MockService_Expecter) SendMessage(ctx interface{}, req interface{}) *MockService_SendMessage_Call {
	return &MockService_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, req)}
}

func (_c *MockService_SendMessage_Call) Run(run func(ctx context.Context, req msg.CreateMessageReq)) *MockService_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(msg.CreateMessageReq))
	})
	return _c
}

func (_c *MockService_SendMessage_Call) Return(_a0 *domain.Message, _a1 error) *MockService_SendMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_SendMessage_Call) RunAndReturn(run func(context.Context, msg.CreateMessageReq) (*domain.Message, error)) *MockService_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
